### ISSUE TITLE
Please add files

### ISSUE THREAD

**Issue by conrad-mac** [GuilhermePFM/sddp#1]
Hi Guilherme,

Thank you for putting up this code - it's very helpful in teaching me about SDDP! I was wondering if you were able to  also upload inputs and code that will help in running the code (e.g. `read_inputs.jl`, `hrload.csv` and `inflow.csv`). 

Kind regards,

Conrad

**Comment by GuilhermePFM** [comment]
Hi Conrad, 

I am glad to hear that this code helped someone to learn about SDDP. This simple SDDP implementation was part of an assignment in a course I took during my masters and I haven't developed it any further, so please keep in mind that it is possible to have bugs in it :). 

I didn't realize there had some code uncommitted in the repository, I will upload the missing code with the example files.

The code is good for learning purposes, but if you are interested in results, or in a more complete SDDP implementation, a good place to look at is Oscar Dowson's SDDP implementation in Julia (https://github.com/odow/SDDP.jl).

Best,

Guilherme

**Comment by conrad-mac** [comment]
Thank you for uploading the missing files, Guilherme :) I will keep in mind that it might have bugs.

I am aware of (and have briefly used) Oscar Dowson's awesome SDDP.jl package but I was after a simpler implementation that I could easily break down and follow line by line to understand some of the concepts better.

Regards,

Conrad

**Comment by GuilhermePFM** [comment]
You are welcome !

Oh, I see. Indeed Oscars' implementation is really complex, hope this one helps you :)
